# Generated by Codex on 2026-01-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_sector(apps, schema_editor):
    Sector = apps.get_model("documents", "Sector")
    Sector.objects.get_or_create(name="Geral", defaults={"is_active": True})


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0015_filter_preset_exclude_terms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserSector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sector",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="members", to="documents.sector"),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="sector_membership", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["user_id"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="sector",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="documents.sector"),
        ),
        migrations.RunPython(create_default_sector, migrations.RunPython.noop),
    ]
