# Generated by Codex on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_sectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersector",
            name="role",
            field=models.CharField(choices=[("admin", "Admin"), ("member", "Member")], default="member", max_length=16),
        ),
    ]
