# Generated by Codex on 2026-01-27

from django.db import migrations, models


def default_modules():
    return {
        "ocr": True,
        "extractor": True,
        "contacts": False,
    }


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0018_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="modules",
            field=models.JSONField(blank=True, default=default_modules),
        ),
    ]
