# Generated by Codex on 2026-01-27

import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0019_sector_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
